apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portfolio-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio-test
    spec:
      containers:
      - name: portfoliotest
        image: us.icr.io/kacz/portfoliotest
        imagePullPolicy: Always
        env:
          - name: RATIONAL_LICENSE_FILE
            value: 27000@rlks.rtp.raleigh.ibm.com
        ports:
          - containerPort: 5443
      imagePullSecrets:
        - name: iks-cr-registry-secret
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: portfolio-test-service
  labels:
    app: portfolio-test
spec:
  type: NodePort
  ports:
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 5443
  selector:
    app: portfolio-test
